### ISSUE TITLE
gif展示如何实验？多种不同角度的动态效果。

### ISSUE THREAD

**Issue by hechengyu132** [anonymous-226/2D-to-3D-Evolution-Transfer#1]
您好！我想问一下项目展示那里多种不同角度的动态鸟gif是怎样实现的，论文里面好像没有找到源码展示呀！谢谢作者抽出时间来回复我。感谢感谢。

**Comment by wrk226** [comment]
渲染的时候调整相机角度就行了，可以参考这里：https://github.com/NVlabs/UMR/blob/15ca8c87c158a238086ef01c9718c9c5773a6659/experiments/demo.py#L98C12-L98C12
