### ISSUE TITLE
模型如何拼接呀，可以完善一下开源项目中experiments的代码吗？方便我们小白上手。

### ISSUE THREAD

**Issue by hechengyu132** [anonymous-226/2D-to-3D-Evolution-Transfer#2]
大佬，您好。刚接触到风格迁移这个方向，对3D风格迁移很感兴趣。您公布的开源代码里面生成出来只有一张2D的平面图，生成3D旋转的效果是不是要obj文件呢？模型如何拼接也不太懂，大佬有时间的话可以完善一下您开源项目中的代码吗？方便我们小白上手，最后祝大佬工作顺利，生活愉快。感谢感谢！

**Comment by wrk226** [comment]
test_df2.py中的self.faces是物体的面，pred_vs是形状迁移结果的顶点位置，两者结合即可获得obj文件。对3D重建和渲染不理解的话可以先看看[UMR](https://github.com/NVlabs/UMR)，我们是在此基础上做的。后续也会慢慢完善我们的代码。
